apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      nodeSelector:
        kubernetes.io/hostname: craventhegreat
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.36.0
          ports:
            - containerPort: 9090
          env:
            - name: LD_SUPERUSER_NAME
              value: "craven"
            - name: LD_SUPERUSER_PASSWORD
              value: "changeme"
          volumeMounts:
            - name: data
              mountPath: /etc/linkding/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-data
