apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
    namespace: ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:pUZC99PUenPVaL0FNhAIRKtjxyfye7xEjmPwcXc6zlzj4bMpK+lpKDjR17P9olle39u0QKmzMtWx8FJV7q5J6YZVTgxyNB4k3g==,iv:/kP4gVUVIhCtU7sf66FxWsQzIdPgLKnh/b+cWkP7vz0=,tag:62Ehq3yKraAZYmJuCbYLug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcXlWSFU3ajdlZE40bG9B
            UWt0aVl2NUJPdW5OTzRpRytGRDdhbzRrYkRBCmEzWlN2U1BGZ0xvR2UwSjArMWNm
            L0lIVTVUc3JzREdUVHd5emU3Kyt6Z28KLS0tIFpyNzNRdUN4WmdUVDhLRFl4ODF5
            Vit0Qk1pbUNuSVRsQUFsdXRhbFIxM0EKdXWGaV3ZWfVAcU2WeCfO/tJRXJ66ttsm
            kgK1AYEZFnWIG9oKoDG5YW7ggxaYlvHWd4DWCpnyC5oqfVOAdmkNjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18w7k4ljg4l63g3f8tyxqp8kpfr376av5ax98374ys9y6zmttxaksajd0q6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T22:34:03Z"
    mac: ENC[AES256_GCM,data:tG/+1E/0eMLJiflOuLVMvvseaNuAA50eEVZ33A6asLCKhGFPIr/VSYzK7+DWLKg8ZYa8tfyO5rCiJc46SWhijfh/oZkUSVavRMxwiQ3AHporSY0DYgfvUNjYzAZCzoUHtp5ubyVvv5dILZtQl11ue61NMBUy3hC4ITR5c/el3Ks=,iv:NHFHgDLi9Y68ZYNwSfadeASh2XfmyvKfj7Nj9F8NapE=,tag:OWQva0REZ4gnfA6dLupXoA==,type:str]
    version: 3.13.3
