apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:X2VHibrs,iv:FYDlVuJDRXzaEwGsz8a50lmIhc8lcdCcr0cHv5xpVxM=,tag:ghU1HcQqqKs6LA054VHmPA==,type:str]
    admin-password: ENC[AES256_GCM,data:AJ4KLThjhKY=,iv:50GAx0tNpPedMTe/7OLnG2gRQ2bK744p2vimA119gSo=,tag:UjADdKU4tfzLX6/HOnGqgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSFI5V3pXWUo3S0tKQURN
            clVpL01tMzhyR0k2Y0NDbDZoVEFBTGRkMUR3CnZlRkNOZkJhWU1aSUphUStEd2wy
            QnBtRXV1eFllWnhLQzg1VVlLbHIrVncKLS0tIHVhNWRXL2EvQjFBV2FPMVAxQ0U1
            OUlDYTlxVHkxaUFvdUVnaXpEMmRYQ0UKjU3hyqrcguCxQOkSb1jbeQRQ5EnwFKS7
            ZZwY//4tXI3c21vHTwXD9ymSepnQS9V8x4MyU1abQ5BPA31ARn6lOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18w7k4ljg4l63g3f8tyxqp8kpfr376av5ax98374ys9y6zmttxaksajd0q6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T02:35:04Z"
    mac: ENC[AES256_GCM,data:6FoZImtlVAqw/G+FX5VrpMqaJEtSQyhbWpQy3LIONilbvK2ekFbhFRXanF6oquXKs3E66Ojq8bLLUaQqEp+/DKAXs2ICInF9oqimA4yGx8X3Z+qrhb5hm02fAZecbV08bmkgw1V8EiSz0l6XLaOWAAt8v04fbA9kY3M+8WARvps=,iv:ibp6njIQY9ixjZG9uKNXfuV0AKdy5mOsgWZWECFU8N0=,tag:mN1mY4+NladEEn1morQMUw==,type:str]
    version: 3.13.3
