apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: homelab-kubecraft
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: links.projectpattie.com
      service: http://linkding.linkding.svc.cluster.local:9090
    - hostname: home.projectpattie.com
      service: http://homepage.homepage.svc.cluster.local:3000
    - hostname: mealie.projectpattie.com
      service: http://mealie.mealie.svc.cluster.local:9000
    - hostname: ntfy.projectpattie.com
      service: http://ntfy.ntfy.svc.cluster.local:8080
    - service: http_status:404
