apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:q/nzy6HjPMM/L8OIIEaM8Cxq6mMeIOQzypVo+abhZx1HVD7RaLqw/oI7kM7AiMqVbiqZy5p1Oi0qg+bi7RqviUCckmlFwvEvw+KmU3z8JmFN9N7BG/JvXHpUprPBpPmrFSZ8TY9k5rf/+hgmfMWw+oXgtXgvmbwpmRefKA3BXl24lvE+X7DiDLV7H0/HlQ1hyqB8w7PXD9cDDKrM9wgqeFBsvPfLd9cmAR5hkNy1Xmn8geIV//t5ChtdOeUQCnBcAEk2y9RbtasnEn4AcLGoevNLAmFLzC7dguDUDzDKferiq5g1wLM4I5PtHrE=,iv:7+imBZXCVXBObdyyGurYnaQAmXtaQV3FPGJ+BzT3AAQ=,tag:KvBvZC3HeJXaegRK+R+UHg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aGZ0T3Y4REZCekdmMlZB
            MzZJd0lXaTFkdjRkR1BFd2ptTFJ4UitVUzJvCjdEUTRxUG5mOTU1bmoydUNXQVFw
            cE5XaGllZDNGNkpZVUlNdW53OUNJeW8KLS0tIFZKNzcxMEhhRUNHdGlUTEtmM3gz
            cHN2eFJFYnZCTnJ1ZTJEMWpqTTQ2WFEK/aZCg+aMuApNK3vdZK2D2v72Fsc6vIyv
            kwvQCivTiO6GuH1Liyjn0SsEbKMyoGyCn6sc96+fr23mLEtYn0Kwqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18w7k4ljg4l63g3f8tyxqp8kpfr376av5ax98374ys9y6zmttxaksajd0q6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T01:03:51Z"
    mac: ENC[AES256_GCM,data:8M70Wq6AoD/78uJiBccO87Ak0VCMwobJdEqFSNgIprVWy5bNkNki2c39ATObhgTFijDHv05nMTwNdXD46xSKtM4zwt/z4jTbpcRMzNK1YI+8EjKpzakm0MUqDO7P1jsAFdC2K5w4240BQpvVClE+5QTvTJzllyrX9SAv/qvV8yc=,iv:deIzjqjALgekD215m9YV6XNvWS73vmrthkZHC2LjCSs=,tag:XEjOWCPJHweq3QnbUDXLVw==,type:str]
    version: 3.13.3
