apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/linkding
  - ../base/cloudflared
  - ../base/homepage
  - ../base/mealie
  - ../base/ntfy
  - ../base/littlelink
