apiVersion: v1
kind: Secret
metadata:
    name: linkding-superuser
    namespace: linkding
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:gtge660g,iv:zcT87sC2YIeXTHKrBwuQOyRbLkdJr1FVibI1/D4KQIc=,tag:pQvfmL+Rsspj3wa7WWPLeQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:LFaooYn+rBs=,iv:16VMs3jRuZXX9ovzrUiyEVewMDo8yy4YQASsIYk0Uh4=,tag:cbTMz+XcmfY6ifkXcHMREQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z1JoNUh2Mk1wV1BRS2s5
            cHMreWhrYnZhUEtwVnhKZzVQbVYrejdRbWgwClVURVNmTVJIZ3M2QjBuUkdEUWtH
            ZGxpZTl6b01ZNFAzSi9jY2UwbWc2MjQKLS0tIDJIekc0SFRYMVhKL2kvSWREN21j
            b0MrcTB0Z2FXQVpvT1lTNkExQS9YSUEKLoSc5b3TvO2pCi8ZYm0AJjlk/+WlWJ/4
            Y3Nz6+tkDtBasJCt4D/rQYlhffWzyNG8nGhYg3kJ7GrijfkEXCi25g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18w7k4ljg4l63g3f8tyxqp8kpfr376av5ax98374ys9y6zmttxaksajd0q6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T14:50:24Z"
    mac: ENC[AES256_GCM,data:aQCAv8xdgSXs/266Jdt+2GvMGm0+lEhQxvsRCLIXCwYK8zSqXV5PthQbccnq0q9rvXqY2t8BjnBc3IKXtjDlFJ/3g5rLRQxuVzBJBTrLKEGcXUC+wVE4ilkiliN7tx4sBUjijAO5CgBnBQPi3VN3APAV2ReB/y3RofYauiuyuiA=,iv:HojBJKEV2hnqFLp4eFS3oMDSekKUECBK8DhRf42W/Z4=,tag:sswrUULUQxMUq/jL0EOPOw==,type:str]
    version: 3.13.3
